import pg from "pg";
const { Pool } = pg;

const pool = new Pool({
  connectionString: "postgresql://neondb_owner:npg_ETNb9slRY6WA@ep-billowing-sound-aydq8obx-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
});

const hoardingsData = [
  { city: 'Madurai', location: 'Goripalayam AV Bridge ', width: 22, height: 30 },
  { city: 'Madurai', location: 'Kalavasal Guru Theater Vaigai Over Bridge ', width: 40, height: 25 },
  { city: 'Madurai', location: 'Airport Mandela Nagar Junction ', width: 60, height: 30 },
  { city: 'Madurai', location: 'Airport Road  Nr HCL (Towards Madurai) ', width: 95, height: 30 },
  { city: 'Madurai', location: 'Airport Road Nr HCL ', width: 95, height: 30 },
  { city: 'Madurai', location: 'Mattuthavani Bus Stand Nr Saravana Stores', width: 47, height: 28 },
  { city: 'Madurai', location: 'Mattuthavani Bus Stand Nr Saravana Stores', width: 47, height: 25 },
  { city: 'Madurai', location: 'Anna Nagar Vandiyur Toll Gate ', width: 20, height: 25 },
  { city: 'Madurai', location: 'Anna Nagar Vadiyur Toll Gate Opp RIO Hospital Towards Airport  ', width: 20, height: 25 },
  { city: 'Madurai', location: 'Vandiyur Toll Gate Towards Madurai City', width: 40, height: 30 },
  { city: 'Madurai', location: 'Arapalayam Junction', width: 20, height: 30 },
  { city: 'Madurai', location: 'Anna Nagar Apollo', width: 33, height: 33 },
  { city: 'Madurai', location: 'Thiruparakundram towards Madurai', width: 55, height: 25 },
  { city: 'Madurai', location: 'Thiruparakundram towards Thirunagar', width: 55, height: 25 },
  { city: 'Madurai', location: 'Periyar Bus Stand ', width: 50, height: 15 },
  { city: 'Madurai', location: 'Periyar Bus Stand ', width: 35, height: 20 },
  { city: 'Madurai', location: 'Nethaji Road Periyar Bus Stand Front ', width: 20, height: 20 },
  { city: 'Madurai', location: 'Nethaji Road Periyar Bus Stand Back ', width: 20, height: 20 },
  { city: 'Madurai', location: 'Simmakkal Junction ', width: 20, height: 20 },
  { city: 'Madurai', location: 'Sethupathi School Simmakkal ', width: 45, height: 28 },
  { city: 'Madurai', location: 'Simmakkal Junction - R', width: 30, height: 25 },
  { city: 'Madurai', location: 'Simmakkal Junction - L', width: 30, height: 25 },
  { city: 'Madurai', location: 'Simmakkal Junction ( Towards Periyar )', width: 30, height: 25 },
  { city: 'Madurai', location: 'Simmakkal Vakil New Street  - L', width: 20, height: 25 },
  { city: 'Madurai', location: 'Simmakkal Vakil New Street  - R', width: 20, height: 25 },
  { city: 'Madurai', location: 'Railway Junction opp', width: 40, height: 13 },
  { city: 'Madurai', location: 'Simmakkal Sunday Market ', width: 20, height: 25 },
  { city: 'Madurai', location: 'Kalavasal Junction', width: 20, height: 20 },
  { city: 'Madurai', location: 'Kalavasal Junction', width: 20, height: 25 },
  { city: 'Madurai', location: 'Kalavasal Junction Fenner', width: 20, height: 20 },
  { city: 'Madurai', location: 'Andalpuram Bridge', width: 20, height: 15 },
  { city: 'Madurai', location: 'Madura College Over Bridge ', width: 22, height: 20 },
  { city: 'Madurai', location: 'Madura College Over Bridge ', width: 25, height: 18 },
  { city: 'Madurai', location: 'Anna Nagar IT Park Nr HCL', width: 50, height: 20 },
  { city: 'Madurai', location: 'Anna Nagar Pandikovil Junction Roundana ', width: 40, height: 15 },
  { city: 'Madurai', location: 'Anna Nagar Pandikovil', width: 30, height: 25 },
  { city: 'Madurai', location: 'Othakadai Towards Mattuthavani Bus Stand ', width: 40, height: 20 },
  { city: 'Madurai', location: 'Towards Airport  Nr D Mart', width: 25, height: 20 },
  { city: 'Madurai', location: 'Airport Towards City  Avaniyapuram D Mart  ', width: 25, height: 20 },
  { city: 'Madurai', location: 'Airport Towards Madurai City', width: 20, height: 20 },
  { city: 'Madurai', location: 'Othakadai Nr Madras High Court', width: 20, height: 20 },
  { city: 'Madurai', location: 'Othakadai towards Mattuthavani  Bus Stand ', width: 20, height: 30 },
  { city: 'Madurai', location: 'Othakadai', width: 30, height: 15 },
  { city: 'Madurai', location: 'Towards Airport Maandela Nagar', width: 40, height: 25 },
  { city: 'Madurai', location: 'Athisayam theme park paravai', width: 50, height: 20 },
  { city: 'Madurai', location: 'Paravai  Back ( Towards Vadipatti ) ', width: 25, height: 20 },
  { city: 'Madurai', location: 'Paravai  Front (Towards Madurai ) ', width: 25, height: 25 },
  { city: 'Madurai', location: 'Paravai (Towards City) ', width: 40, height: 30 },
  { city: 'Madurai', location: 'Ramnad Road Velammal Medical College Roundana ', width: 70, height: 25 },
  { city: 'Madurai', location: 'Ramnad Road Velammal Medical College Roundana ', width: 20, height: 20 },
  { city: 'Madurai', location: 'Theppakulam Viraganoor', width: 20, height: 30 },
  { city: 'Madurai', location: 'Melur Bus Stand Opp', width: 25, height: 20 },
  { city: 'Madurai', location: 'Melur Bus Stand Opp', width: 30, height: 20 },
  { city: 'Madurai', location: 'Sivagangai Road Karupaiurani ', width: 30, height: 20 },
  { city: 'Madurai', location: 'Sivagangai Towards Madurai Karupayurani ', width: 30, height: 20 },
  { city: 'Madurai', location: 'TPK Road Nr Mannar College ', width: 45, height: 20 },
  { city: 'Madurai', location: 'TPK Road Bridge', width: 40, height: 30 },
  { city: 'Madurai', location: 'Thanakankulam Ford Showroom', width: 20, height: 20 },
  { city: 'Madurai', location: 'Thirunagar  Towards Madurai ', width: 20, height: 20 },
  { city: 'Madurai', location: 'Thirunagar  Towards Tirumangalam ', width: 20, height: 20 },
  { city: 'Madurai', location: 'Anna Nagar Suguna Stores', width: 20, height: 30 },
  { city: 'Madurai', location: 'Kamarajar Salai', width: 70, height: 30 },
  { city: 'Madurai', location: 'Kamarajar Salai Big Cinimas ', width: 35, height: 15 },
  { city: 'Madurai', location: 'Kuruvikaran salai Nr Kamarajar Salai Bigcinimas  - L', width: 80, height: 25 },
  { city: 'Madurai', location: 'Kuruvikaran salai Nr Kamarajar Salai Bigcinimas  - R', width: 80, height: 25 },
  { city: 'Madurai', location: 'Anna Nagar Aravind Eye Hospital ', width: 50, height: 25 },
  { city: 'Madurai', location: 'Kamarajar Salai Vilakuthun Near', width: 25, height: 20 },
  { city: 'Madurai', location: 'Kamarajar Salai', width: 25, height: 30 },
  { city: 'Madurai', location: 'Vilakuthun Signal', width: 30, height: 30 },
  { city: 'Madurai', location: 'Vilakuthun Signal Towards Meenakshi Temple ', width: 13, height: 25 },
  { city: 'Madurai', location: 'Vilakuthun Signal Towards Meenakshi Temple ', width: 30, height: 22 },
  { city: 'Madurai', location: 'Vilakuthun Market', width: 16, height: 25 },
  { city: 'Madurai', location: 'Vilakuthun Market Thermuti', width: 17, height: 12 },
  { city: 'Madurai', location: 'Simmakkal Nelpettai', width: 12, height: 20 },
  { city: 'Madurai', location: 'Surveyor Colony Near Mattuthavani ', width: 40, height: 20 },
  { city: 'Madurai', location: 'Surveyor Colony Three Road Junction ', width: 20, height: 15 },
  { city: 'Madurai', location: 'Surveyor Colony Mattuthavani Road Junction ', width: 25, height: 18 },
  { city: 'Madurai', location: 'Iyarbanglow Towards Moondurumavadi ', width: 20, height: 30 },
  { city: 'Madurai', location: 'Algarkovil Road Kadachandal', width: 22, height: 20 },
  { city: 'Madurai', location: 'Algarkovil Road Kadachandal ( Towards City)', width: 40, height: 30 },
  { city: 'Madurai', location: 'Pudur Bus Stand', width: 40, height: 40 },
  { city: 'Madurai', location: 'Thallakulam', width: 12, height: 23 },
  { city: 'Madurai', location: 'Thirupalai Yadava College ', width: 30, height: 20 },
  { city: 'Madurai', location: 'Oomachikulam Flyover Towards Natham ', width: 20, height: 25 },
  { city: 'Madurai', location: 'Natham Towards Madurai Iyar Bunglow ', width: 20, height: 25 },
  { city: 'Madurai', location: 'Alanganallur Road Sikantharchavadi Radio Station ', width: 30, height: 30 },
  { city: 'Madurai', location: 'Airport Near Perunkudi', width: 35, height: 30 },
  { city: 'Madurai', location: 'Ramnad Road Silaiman', width: 25, height: 20 },
  { city: 'Madurai', location: 'Nagamalai Puthukottai', width: 14, height: 18 },
  { city: 'Madurai', location: 'Viratipathu', width: 20, height: 20 },
  { city: 'Madurai', location: 'Tirunelveli Towards Madurai Entrance Tirumangalam Tollgate ', width: 80, height: 30 },
  { city: 'Madurai', location: 'Madurai - Tirunelveli Tirumangalam Toll Gate ', width: 40, height: 20 },
  { city: 'Madurai', location: 'Kappalur Nissan Showroom Towards Madurai City ', width: 80, height: 30 },
  { city: 'Madurai', location: 'Kappalur Nissan Showroom Towards Thirumangalam ', width: 80, height: 30 },
  { city: 'Madurai', location: 'Thoppur Kappalur', width: 30, height: 30 },
  { city: 'Madurai', location: 'Madurai - Smayanallur Over Bridge -Front Board', width: 100, height: 30 },
  { city: 'Madurai', location: 'Madurai  - Smayanallur Over Bridge -Back  Board', width: 100, height: 20 },
  { city: 'Madurai', location: 'Samayanallur Over Bridge', width: 60, height: 25 },
  { city: 'Madurai', location: 'Dindigul To Madurai Thanichiyam', width: 30, height: 30 },
  { city: 'Madurai', location: 'Melur Main Road near  TVS Gowdown ', width: 50, height: 20 },
  { city: 'Madurai', location: 'Melur Main Road Tollgate', width: 80, height: 30 },
  { city: 'Madurai', location: 'Madurai Kamarajar University Front', width: 20, height: 25 },
  { city: 'Madurai', location: 'Madurai Kamarajar University Back', width: 25, height: 20 },
  { city: 'Madurai', location: 'Madurai Tutucorin Road Valayankulam Tollgate', width: 50, height: 30 },
  { city: 'Madurai', location: 'Thirupuvanam Junction', width: 40, height: 15 },
  { city: 'Madurai', location: 'Usilampatti Bus Stand', width: 25, height: 20 },
  { city: 'Madurai', location: 'B B Kulam', width: 20, height: 15 },
  { city: 'Madurai', location: 'Karupayurani nr solamalai college', width: 25, height: 25 },
  { city: 'Madurai', location: 'Thanakankulam ', width: 60, height: 25 },
  { city: 'Madurai', location: 'Thirunagar - R', width: 30, height: 25 },
  { city: 'Madurai', location: 'Thirunagar - L', width: 30, height: 25 },
  { city: 'Madurai', location: 'Palanganatham Junction', width: 20, height: 25 },
  { city: 'Chennai', location: 'Pattabiram', width: 35, height: 30 },
  { city: 'Chennai', location: 'Avadi Bridge', width: 25, height: 30 },
  { city: 'Ramnad', location: 'Ramnad Entrance Tollgate', width: 60, height: 25 },
  { city: 'Rajapalayam', location: 'Rajapalayam Sankarankovil Road ', width: 25, height: 30 },
  { city: 'Rajapalayam', location: 'Rajapalayam Town Front', width: 25, height: 25 },
  { city: 'Rajapalayam', location: 'Rajapalayam Town  Back ', width: 25, height: 25 },
  { city: 'Rajapalayam', location: 'Rajapalayam Krishnan kovil vpm College', width: 40, height: 30 },
  { city: 'Rajapalayam', location: 'Rajapalayam Manjammal Polytechnic Rajapalayam Entrance', width: 20, height: 30 },
  { city: 'Rajapalayam', location: 'Rajapalayam Nachiar Mill Front', width: 20, height: 25 },
  { city: 'Rajapalayam', location: 'Rajapalayam Nachiar Mill Back', width: 20, height: 25 },
  { city: 'Rajapalayam', location: 'Rajapalayam ', width: 40, height: 15 },
  { city: 'Paramakudi', location: 'Paramakudi Bus Stand', width: 30, height: 20 },
  { city: 'Sivagangai', location: 'Sivagangai City Entrance Nr Priest University ', width: 25, height: 17 },
  { city: 'Sivagangai', location: 'Madurai To Sivagangai Entrance ', width: 25, height: 20 },
  { city: 'Sivagangai', location: 'Sivagangai To Madurai Sivagangai Entrance', width: 30, height: 20 },
  { city: 'Viruthunagar', location: 'Viruthunagar Main Bazzar ', width: 20, height: 18 },
  { city: 'Viruthunagar', location: 'Viruthunagar City Entrance Kumaralingapuram ', width: 50, height: 30 },
  { city: 'T.Kallupatti', location: 'T.Kallupatti', width: 15, height: 15 },
  { city: 'T.Kallupatti', location: 'T.Kallupatti', width: 12, height: 10 },
  { city: 'Sathur', location: 'Sathur ( Towards Kovilpatti) ', width: 30, height: 20 },
  { city: 'Sathur', location: 'Sathur ( Towards Madurai)', width: 30, height: 20 },
  { city: 'Viruthunagar', location: 'Viruthu Nagar ( Arupukottai Towards VNR ) ', width: 25, height: 25 },
  { city: 'Viruthunagar', location: 'Viruthu Nagar (Towards Aruppukottai )', width: 25, height: 25 },
  { city: 'Viruthunagar', location: 'Viruthunagar  Collector Office ( Towards Viruthu Nagar)  – L ', width: 36, height: 25 },
  { city: 'Viruthunagar', location: 'Viruthunagar Collector Office – R ', width: 36, height: 25 },
  { city: 'Coimbatore', location: 'Pollachi road Kinatrukadavu', width: 60, height: 20 },
  { city: 'Coimbatore', location: 'Annur Road Kurumbampalayam', width: 40, height: 15 },
  { city: 'Coimbatore', location: 'Trichi Road Chinnakodankipalayam front', width: 60, height: 15 },
  { city: 'Coimbatore', location: 'Trichi Road Chinnakodankipalayam Back', width: 60, height: 15 },
  { city: 'Coimbatore', location: 'Mettupalayam Road Narasingapalayam ', width: 56, height: 20 },
  { city: 'Coimbatore', location: 'Coimbatore Karanampettai Front', width: 60, height: 25 },
  { city: 'Coimbatore', location: 'Coimbatore Karanampettai Back', width: 60, height: 10 },
  { city: 'Coimbatore', location: 'Avinashi Road Karumathampatti', width: 60, height: 20 },
  { city: 'Thoothukudi', location: 'Tutucorin Nila sea foods', width: 40, height: 20 },
  { city: 'Tirunelveli', location: 'Kayatharu Tollgate-Front', width: 70, height: 20 },
  { city: 'Tirunelveli', location: 'kayatharu Tollgate-Back', width: 70, height: 30 },
  { city: 'Tirunelveli', location: 'Thachanallur', width: 60, height: 20 },
  { city: 'Tirunelveli', location: 'Thachanallur', width: 30, height: 20 },
  { city: 'Tirunelveli', location: 'Ambai To Nellai Road', width: 30, height: 12 },
  { city: 'Tirunelveli', location: 'Cheranmaadevi Bus Stand ', width: 20, height: 15 },
  { city: 'Tirunelveli', location: 'Cheranmaadevi Bus Stand ', width: 30, height: 15 },
  { city: 'Tirunelveli', location: 'Tirunelveli - Gangaikondan ', width: 35, height: 25 },
  { city: 'Tirunelveli', location: 'Tirunelveli Junction ', width: 50, height: 25 },
  { city: 'Tirunelveli', location: 'Tirunelveli ( Towards Kutralam) ', width: 25, height: 25 },
  { city: 'Tirunelveli', location: 'Tirunelveli ( Kutralam Towards City Entrance )', width: 25, height: 25 },
  { city: 'Tirunelveli', location: 'Tirunelveli KTC Nagar - Front', width: 30, height: 25 },
  { city: 'Tirunelveli', location: 'Tirunelveli KTC Nagar - Back', width: 30, height: 25 },
  { city: 'Palani', location: 'Palani Chathirapatti Towards Palani ', width: 30, height: 20 },
  { city: 'Palani', location: 'Palani Towards Ottanchathiram Chathirapatti ', width: 30, height: 20 },
  { city: 'Thenkasi', location: 'Elanji', width: 50, height: 20 },
  { city: 'Sivakasi', location: 'Sivakasi Bus Stand ', width: 25, height: 20 },
  { city: 'Sivakasi', location: 'Sivakasi Thiruthangal Railwaygate', width: 20, height: 20 },
  { city: 'Sivakasi', location: 'Sathur Road Front', width: 30, height: 20 },
  { city: 'Sivakasi', location: 'Sathur Road Back', width: 30, height: 15 },
  { city: 'Sivakasi', location: 'Viruthunagar Towards Sivakasi VV Nursing College ', width: 60, height: 15 },
  { city: 'Sivakasi', location: 'Sivakasi Towards Viruthu Nagar  VV Nursing College ', width: 60, height: 30 },
  { city: 'Theni', location: 'Veerapandi', width: 80, height: 25 },
  { city: 'Theni', location: 'Theni toll gate Front', width: 70, height: 25 },
  { city: 'Theni', location: 'Theni toll gate Back', width: 70, height: 25 },
  { city: 'Theni', location: 'Andipatti Towards Theni', width: 25, height: 25 },
  { city: 'Theni', location: 'Theni Towards Andipatti', width: 25, height: 25 },
  { city: 'Theni', location: 'Theni Allinagaram Towards Periyakulam ', width: 25, height: 20 },
  { city: 'Theni', location: 'Theni Allinagaram Towards Theni', width: 25, height: 20 },
  { city: 'Theni', location: 'Theni Kunnur Tollgate', width: 50, height: 25 },
  { city: 'Theni', location: 'Bodi Bus Stand Nr ', width: 20, height: 25 },
  { city: 'Theni', location: 'Periyakulam Towards Theni', width: 80, height: 25 },
  { city: 'Theni', location: 'Theni Towards Periyakulam', width: 80, height: 25 },
  { city: 'Cumbam', location: 'Uthamapalayam', width: 30, height: 20 },
  { city: 'Cumbam', location: 'Uthamapalayam', width: 30, height: 20 },
  { city: 'Aruppukottai', location: 'Sowdampika College Front', width: 30, height: 20 },
  { city: 'Aruppukottai', location: 'sowdampika College Back', width: 30, height: 20 }
].map(item => ({
  ...item,
  owner_name: 'SS Advertisers',
  contact_number: 'N/A',
  rent_amount: 0,
  rent_status: 'Pending'
}));

async function run() {
  try {
    console.log('Deleting existing hoardings...');
    await pool.query('DELETE FROM hoardings');

    console.log('Inserting new hoardings...');
    for (const item of hoardingsData) {
      await pool.query(
        `INSERT INTO hoardings (city, location, width, height, owner_name, contact_number, rent_amount, rent_status)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
        [item.city, item.location, item.width, item.height, item.owner_name, item.contact_number, item.rent_amount, item.rent_status]
      );
    }
    console.log('Successfully inserted', hoardingsData.length, 'hoardings.');
  } catch (error) {
    console.error('Error:', error);
  } finally {
    await pool.end();
  }
}

run();
