CREATE TABLE hoardings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location TEXT NOT NULL,
    width DECIMAL NOT NULL,
    height DECIMAL NOT NULL,
    total_area DECIMAL GENERATED ALWAYS AS (width * height) STORED,
    owner_name TEXT NOT NULL,
    contact_number TEXT NOT NULL,
    rent_amount DECIMAL NOT NULL,
    rent_status TEXT CHECK (rent_status IN ('Paid', 'Pending')) DEFAULT 'Pending',
    last_paid_date DATE,
    next_due_date DATE,
    notes TEXT,
    latitude TEXT,
    longitude TEXT,
    is_owned BOOLEAN DEFAULT FALSE,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Campaigns table
CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_info TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    hoarding_id BIGINT REFERENCES hoardings(id) ON DELETE CASCADE,
    internal_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create users table (profiles)
CREATE TABLE profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT,
    phone_number TEXT,
    email TEXT UNIQUE,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, phone_number, avatar_url)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call handle_new_user on signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Enable Row Level Security
ALTER TABLE hoardings ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;

-- Create policies (allowing all access for now, in a real app you'd restrict this)
CREATE POLICY "Public full access hoardings" ON hoardings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access campaigns" ON campaigns FOR ALL USING (true) WITH CHECK (true);
