CREATE TABLE hoardings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location TEXT NOT NULL,
    city TEXT DEFAULT 'Chennai',
    width DECIMAL NOT NULL,
    height DECIMAL NOT NULL,
    total_area DECIMAL GENERATED ALWAYS AS (width * height) STORED,
    owner_name TEXT NOT NULL,
    contact_number TEXT NOT NULL,
    rent_amount DECIMAL NOT NULL,
    rent_status TEXT CHECK (rent_status IN ('Paid', 'Pending')) DEFAULT 'Pending',
    last_paid_date DATE,
    next_due_date DATE,
    notes TEXT,
    latitude TEXT,
    longitude TEXT,
    is_owned BOOLEAN DEFAULT FALSE,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Campaigns table
CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_info TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    hoarding_id BIGINT REFERENCES hoardings(id) ON DELETE CASCADE,
    internal_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create users table (profiles)
CREATE TABLE profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT,
    phone_number TEXT,
    email TEXT UNIQUE,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, phone_number, avatar_url)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call handle_new_user on signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Create Purchase Orders table
CREATE TABLE purchase_orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    campaign_id BIGINT REFERENCES campaigns(id) ON DELETE CASCADE,
    hoarding_id BIGINT REFERENCES hoardings(id) ON DELETE CASCADE,
    po_number TEXT NOT NULL,
    po_date DATE NOT NULL DEFAULT CURRENT_DATE,
    vendor_name TEXT NOT NULL,
    description TEXT NOT NULL,
    total_amount DECIMAL NOT NULL,
    paid_amount DECIMAL DEFAULT 0,
    balance_amount DECIMAL DEFAULT 0,
    status TEXT CHECK (status IN ('draft', 'sent', 'partial', 'paid', 'cancelled')) DEFAULT 'draft',
    payment_terms TEXT DEFAULT 'Due on Receipt',
    due_date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add campaign and PO tracking columns to ledger
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS campaign_id BIGINT REFERENCES campaigns(id) ON DELETE SET NULL;
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS po_id UUID REFERENCES purchase_orders(id) ON DELETE SET NULL;
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS transaction_type TEXT CHECK (transaction_type IN ('po_payment', 'rent', 'other')) DEFAULT 'other';
ALTER TABLE ledger ADD COLUMN IF NOT EXISTS reference_number TEXT;

-- Add PO summary columns to campaigns (for quick dashboard stats)
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS po_status TEXT CHECK (po_status IN ('none', 'pending', 'partial', 'paid')) DEFAULT 'none';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS total_po_amount DECIMAL DEFAULT 0;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS paid_po_amount DECIMAL DEFAULT 0;

-- Enable Row Level Security
ALTER TABLE hoardings ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;

-- Create policies (allowing all access for now, in a real app you'd restrict this)
CREATE POLICY "Public full access hoardings" ON hoardings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access campaigns" ON campaigns FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access purchase_orders" ON purchase_orders FOR ALL USING (true) WITH CHECK (true);

-- Function to auto-update updated_at on purchase_orders
CREATE OR REPLACE FUNCTION update_purchase_order_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_purchase_order_timestamp
  BEFORE UPDATE ON purchase_orders
  FOR EACH ROW EXECUTE FUNCTION update_purchase_order_timestamp();

-- Flex Printing Status table
CREATE TABLE flex_printing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT REFERENCES campaigns(id) ON DELETE SET NULL,
    hoarding_id BIGINT REFERENCES hoardings(id) ON DELETE SET NULL,
    printing_type TEXT NOT NULL CHECK (printing_type IN ('outsource', 'own_printing')),
    flex_size TEXT,
    quantity INTEGER DEFAULT 1,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    -- Outsource fields
    vendor_name TEXT,
    vendor_contact TEXT,
    assignment_date DATE,
    expected_completion DATE,
    outsource_status TEXT CHECK (outsource_status IN ('assigned', 'in_progress', 'completed', 'delayed')),
    outsource_cost DECIMAL(12,2),
    -- Own printing fields
    material_cost DECIMAL(12,2),
    labor_cost DECIMAL(12,2),
    total_cost DECIMAL(12,2) GENERATED ALWAYS AS (COALESCE(material_cost, 0) + COALESCE(labor_cost, 0)) STORED,
    ledger_entry_id UUID REFERENCES ledger(id) ON DELETE SET NULL,
    payment_status TEXT CHECK (payment_status IN ('pending', 'partial', 'paid'))
);

ALTER TABLE flex_printing ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access flex_printing" ON flex_printing FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER set_flex_printing_timestamp
  BEFORE UPDATE ON flex_printing
  FOR EACH ROW EXECUTE FUNCTION update_purchase_order_timestamp();
